# flyway.toml

# More information on the parameters can be found here: https://documentation.red-gate.com/flyway/flyway-cli-and-api/configuration/parameters

# [environments.sample]
# url = "jdbc:h2:mem:db"
# user = "sample user"
# password = "sample password"
# # jarDirs = ["path/to/java/migrations"]
# # driver =
# # schemas =
# # connectRetries =
# # connectRetriesInterval =
# # initSql =
# # jdbcProperties =
# # resolvers =
# flyway.toml

[flyway]
locations = ["filesystem:./database/migrations"]

[environments.flyway]
url = "jdbc:postgresql://audio-archive-psql-db2.cxq8xikgucfb.us-east-2.rds.amazonaws.com:5432/postgres?sslmode=prefer"
user = "postgres"
password = "postgres-secret"


# [flyway.check]
# buildEnvironment = "build"
