# flyway.toml

[flyway]
locations = ["filesystem:./database/migrations"]

[environments.flyway]
# url = "jdbc:postgresql://localhost/flyway_db"
url = "jdbc:postgresql://audio-archive-psql-db2.cxq8xikgucfb.us-east-2.rds.amazonaws.com:5432/postgres?sslmode=prefer"
user = "postgres"
password = "postgres-secret"
