# flyway.toml

[flyway]
locations = ["filesystem:./database/migrations"]
sqlMigrationPrefix=""
sqlMigrationSeparator="_"
sqlMigrationSuffixes = ['.sql']

[environments.flyway]
url = "jdbc:postgresql://localhost/audio_archive_production"
# url = "jdbc:postgresql://audio-archive-psql-db2.cxq8xikgucfb.us-east-2.rds.amazonaws.com:5432/postgres?sslmode=prefer"
# user = "postgres"
# password = "postgres-secret"

# url="jdbc:postgresql://audio-archive-psql-db2.cxq8xikgucfb.us-east-2.rds.amazonaws.com:5432/postgres"
user="postgres"
password="postgres-secret"
# Additional Flyway configurations can be added as needed
# flyway.url="jdbc:postgresql://audio-archive-psql-db2.cxq8xikgucfb.us-east-2.rds.amazonaws.com:5432/postgres?ssl=true&sslmode=verify-full"
