CREATE TYPE key AS ENUM(
    'B Major'
    , 'F♯/G♭ Major'
    , 'D♭ Major'
    , 'A♭ Major'
    , 'E♭ Major'
    , 'B♭ Major'
    , 'F Major'
    , 'C Major'
    , 'G Major'
    , 'D Major'
    , 'A Major'
    , 'E Major'
    , 'A♭ Minor'
    , 'E♭ Minor'
    , 'B♭ Minor'
    , 'F Minor'
    , 'C Minor'
    , 'G Minor'
    , 'D Minor'
    , 'A Minor'
    , 'E Minor'
    , 'B Minor'
    , 'F♯/G♭ Minor'
    , 'D♭ Minor'
);

-- DROP TYPE key;
